module.exports = [
  "Desenvolvedor",
  "Desenvolvedor Full Stack",
  "Desenvolvedor Backend",
  "Desenvolvedor Frontend",
  "Estágio Desenvolvimento",
  "Programador",
  "Engenheiro de Software",
  "Desenvolvedor Web",
  "Desenvolvedor Mobile",
  "Desenvolvedor React",
  "Desenvolvedor Node.js",
  "Desenvolvedor Python",
  "Desenvolvedor Java",
  "Desenvolvedor .NET",
  "Desenvolvedor C#",
  "Desenvolvedor JavaScript",
  "Desenvolvedor PHP",
  "Desenvolvedor Ruby",
  "Desenvolvedor Android",
  "Desenvolvedor iOS",
  "Desenvolvedor DevOps",
  "Arquiteto de Software",
  "Analista de Sistemas",
  "Desenvolvedor de Jogos",
  "Desenvolvedor de Inteligência Artificial",
  "Desenvolvedor de Machine Learning",
  "Desenvolvedor de Blockchain",
  "Desenvolvedor de Segurança",
  "Desenvolvedor de Banco de Dados",
  "Desenvolvedor QA",
  "Desenvolvedor Remoto",
  "Desenvolvedor Home Office",
  "Programador Remoto",
  "Engenheiro de Software Remoto",
  "Desenvolvedor Full Stack Remoto",
  "Desenvolvedor Backend Home Office",
  "Desenvolvedor Frontend Remoto",
  "Desenvolvedor React Remoto",
  "Desenvolvedor Node.js Home Office",
  "Desenvolvedor Python Remoto",
  "Desenvolvedor Java Home Office",
  "Analista de Sistemas Remoto",
  "DevOps Remoto",
  "QA Remoto"
];